version: '3'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        restart: unless-stopped
        volumes:
            - mysql-data:/var/lib/mysql
        env_file:
            - .docker.env
        networks:
            - php-network

    php:
        container_name: phpfpm_1
        image: php-blog-app
        restart: unless-stopped
        # ports:
        #     - "9000:9000"
        volumes:
            - .:/app:delegated
        env_file:
            - .docker.env
        depends_on:
            - mysql
        networks:
            - php-network

    nginx:
        container_name: nginx_1
        image: nginx:1.17.3-alpine
        command: sh -c "chmod 777 -Rc /app/storage && chmod 777 -Rc /app/bootstrap/cache && nginx -g \"daemon off;\""
        restart: unless-stopped
        ports:
            - "8010:80"
        volumes:
            - .:/app:delegated
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
        networks:
            - php-network
              
volumes:
    mysql-data:

networks:
    php-network: