version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .docker.env
    networks:
      - internal

  php:
    container_name: phpfpm
    image: php-blog-app
    restart: unless-stopped
    # ports:
    #     - "9000:9000"
    volumes:
      - .:/app:delegated
    env_file:
      - .docker.env
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:1.17.3-alpine
    command: sh -c "chmod 777 -Rc /app/storage && chmod 777 -Rc /app/bootstrap/cache && nginx -g \"daemon off;\""
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - .:/app:delegated
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - internal

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - nginx
    networks:
      - web
      - internal

volumes:
  mysql-data:

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
